version: '3.1'
services:
  dev_api:
    image: lotosbin/zentao.api
    build:
      context: .
      dockerfile: zentao.api/Dockerfile
    ports:
      - "5000:80"
    env_file: ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  prd_api:
    image: lotosbin/zentao.api
    ports:
      - "5000:80"